Repository Evgenios95/Car-Rental-System, pull requests merged in 2021-11, with the labels that each got.

#13 Fixing NavBar component logic & css / Modified Input Component
  clientSide/src/components/Input/input.css
  clientSide/src/components/Input/input.jsx
  clientSide/src/components/NavBar/NavBar.css
  clientSide/src/components/NavBar/Navbar.jsx
Labels: enhancement, fixed

#17 Basic customer info - Will be modified later.
  clientSide/src/components/Big components/CustomerInfo.css
  clientSide/src/components/Big components/CustomerInfo.jsx
Labels: enhancement, Changes needed later

#15 Introduced UI Wrapper Coponents
  clientSide/src/App.css
  clientSide/src/ui-components/CRCard.jsx
  clientSide/src/ui-components/CRColumn.jsx
  clientSide/src/ui-components/CRContainer.jsx
Labels: enhancement, Changes needed later

#14 Cleaning Login, added texts
  clientSide/src/components/Login/Login.jsx
  clientSide/src/index.js
  clientSide/src/text/text.js
Labels: enhancement, cleaning

#19 nav small fix
  clientSide/src/components/NavBar/NavBar.css
  clientSide/src/components/NavBar/Navbar.jsx
  clientSide/src/text/text.js
Labels: fixed

#18 Introducing starting page, some more changes
  clientSide/public/images/itu-cars1.jpg
  clientSide/public/manifest.json
  clientSide/src/App.js
  clientSide/src/components/Button/Button.jsx
  clientSide/src/components/Login/Login.jsx
  clientSide/src/components/NavBar/Navbar.jsx
  clientSide/src/components/StartingPageImage/StartingPageImage.css
  clientSide/src/components/StartingPageImage/StartingPageImage.jsx
Labels: enhancement, cleaning

#21 Johha/dropdown
  clientSide/src/App.js
  clientSide/src/components/DropDown/DropDown.css
  clientSide/src/components/DropDown/DropDown.jsx
  clientSide/src/text/text.js
Labels: enhancement, Changes needed later

#23 font fix
  clientSide/src/variables/fonts.css
  clientSide/src/variables/text-composita.css
Labels: fixed
